### ISSUE TITLE
ValueError: Didn't get version tag in the header

### ISSUE THREAD

**Issue by ValdDracula** [cclgroupltd/ccl_chrome_indexeddb#1]
Hello,

I've been trying to retrieve the key/value information from a specific leveldb on Chrome IndexedDB and I keep getting a ValueError exception.

```
ValueError: Didn't get version tag in the header
```

This happens on the records iteration and it crashes on the following verification:
```python
def _read_header(self) -> int:
        tag = self._read_tag()
        if tag != Constants.token_kVersion:
            raise ValueError("Didn't get version tag in the header")
        version = self._read_le_varint()[0]
        return version
```

Apparently my version tag value is 0x01 and it should be 0xff.

This only appears with one specific leveldb. Do you know why is the version tag with this value? Shouldn't it be the 0xff instead of 0x01

**Comment by cclgroupltd** [comment]
Hi there,

I'll need to dive back into the Chrome source to work out what may be happening/if it's allowed to happen. If it's not sensitive, is it possible to share the blob of data which causes the error? Is it every value in the leveldb or do you get through some first? Is the database representative of recent data, or is it a little older?

**Comment by ValdDracula** [comment]
Hello,

**If it's not sensitive, is it possible to share the blob of data which causes the error?**
I prefer not to share the blob because the data is from a Zoom meeting in the browser so I'm not sure what type of information can be stored there regarding my Zoom account. In order to reproduce the leveldb and blob you just need to host a Zoom meeting on the browser and the leveldb and blob will be created. I believe this behaviour will happen to every leveldb and blob related to Zoom web meetings.

**Is it every value in the leveldb or do you get through some first?**
Every value in the leveldb for Zoom raises this exception.

**Is the database representative of recent data, or is it a little older?**
It is recent. The data was created the day I tested it. 2 days ago.

I've tested the script with twitter and Google Drive related blobs and it worked fine. Also those blobs are recent, December 10.

**Comment by cclgroupltd** [comment]
Great, thank you for the details. I will get back to you when I've had a chance to have a look at some data.

**Comment by docelic** [comment]
Same issue. With `print` added in `_read_header`:

```
    def _read_header(self) -> int:
        tag = self._read_tag()
        print('tag/token_kVersion', tag, Constants.token_kVersion)
        if tag != Constants.token_kVersion:
            raise ValueError("Didn't get version tag in the header")
        version = self._read_le_varint()[0]
        return version
```

The output ends up being:

```
<WrappedDatabase: id=1; name=somedb; origin=https_someweb_0@1>
<WrappedObjectStore: object_store_id=1; name=somestore>

tag/token_kVersion b'\xff' b'\xff'
tag/token_kVersion b'\xff' b'\xff'
tag/token_kVersion b'\xff' b'\xff'
tag/token_kVersion b'\xff' b'\xff'
tag/token_kVersion b'\x01' b'\xff'
Traceback (most recent call last):
    for record in store.iterate_records():
    yield from self._raw_db.iterate_records(
    deserializer = ccl_v8_value_deserializer.Deserializer(
    self.version = self._read_header()
    raise ValueError("Didn't get version tag in the header")
ValueError: Didn't get version tag in the header
```

**Comment by cclgroupltd** [comment]
Hi,

Are you able to share the data that raised this error? 
If you comment out the if/raise lines in there, does the code proceed as expected?

**Comment by intelligentpotato** [comment]
Hi,

Thank you for putting so much effort into developing such a tool and open sourcing it.

I am working on recovering Proton Mail messages from cache and ran into the same issue. 

If I comment out the _raise ValueError("Didn't get version tag in the header")_, another exception raises at line 600 of ccl_v8_value_deserializer.py:

```
if func is None:
  raise ValueError(f"Unknown tag {tag}")
```

I am willing to share the dataset with you privately if it helps, just let me know the email where I can send it.

**Comment by cclgroupltd** [comment]
@dg-data thanks for highlighting this - it has highlighted some other changes in recent versions which I also need to address, so I'll be jumping on that as soon as I have a chance.

**Comment by cclgroupltd** [comment]
@dg-data a little more context in case you're interested - on the blob wrapping side of things, it looks like this happens if the serialized data exceeds [kIDBWrapThreshold](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:out/Debug/gen/third_party/blink/public/mojom/indexeddb/indexeddb.mojom-blink-forward.h;drc=e0e0d24aaa54727dc0a8bc4b159ccdf80d3f5d8d;bpv=1;bpt=1;l=87?gsn=kIDBWrapThreshold&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fchromium.googlesource.com%2Fcodesearch%2Fchromium%2Fsrc%2F%2Fmain%3Flang%3Dc%252B%252B%3Fpath%3Dout%2FDebug%2Fgen%2Fthird_party%2Fblink%2Fpublic%2Fmojom%2Findexeddb%2Findexeddb.mojom-blink-forward.h%23LFRPOETqYxIJNLefBC3HDY1FQYmXPB-OK94dZzYefmk) which is 65536 (at the moment). In that case the serialized data is referenced in a blob entry for that key - functionally I think that means that it's in a separate file on disk, but I'm putting together test data at the moment to check exactly what is going on...

**Comment by dg-data** [comment]
@cclgroupltd Hi!
Thanks for your quick reaction. The basic logic stayed untouched in Blink I think, class **IndexedDBExternalObject** and blob handling looks good. The route to the data comes from records with a key where index ID is 3 – the “_external object table_” and the blob info in it. Deserialization of that blob should work,

**Comment by cclgroupltd** [comment]
@dg-data yep, the logic for looking up the external data is already in our module because it's how "File objects" are accessed. It shouldn't be too tricky to plumb that all in.

**Comment by cclgroupltd** [comment]
@dg-data could you give the most recent commit a go if you have suitable test data? It is working with my test data, but if you have real-world data to run it against that would be useful!

**Comment by dg-data** [comment]
@cclgroupltd Thanks for the update. I checked the most recent version and found no mistakes. I tested various records (Blink v.17, 20, 21) including the ones with externally serialized objects. As far as I see it looks pretty good, at least solved the issue I had. Great work, saved my data!

**Comment by cclgroupltd** [comment]
Fantastic. I'll close this issue now then, thanks for you help!
