### ISSUE TITLE
Can you write to indexeddb?

### ISSUE THREAD

**Issue by jose-sampedro** [cclgroupltd/ccl_chrome_indexeddb#17]
I have been able to read the indexeddb file, but I don't know how I can write to it. Any suggestions?

Thank you.

**Comment by cclgroupltd** [comment]
This library is only for reading (and there is no intention to implement writing, sorry).

The easiest way to write to IndexedDB is in the browser via the JavaScript API (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) unless you're specifically trying to do it outside of the browser for research purposes?
